"""
Email Sender for Email Service

Sends emails via SMTP (MailHog in development).
"""
import time
import logging
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from .config import settings

logger = logging.getLogger(__name__)


def send_order_confirmation_email(user_email: str, order_id: int, amount: str, transaction_id: str):
    """
    Send order confirmation email.

    This simulates the 2-second email delay from the monolith,
    but now it happens ASYNCHRONOUSLY - the user doesn't wait!
    """
    logger.info("=" * 80)
    logger.info(f"📧 [Email Service] Sending confirmation email to {user_email}")
    logger.info(f"📦 Order #{order_id} | 💰 ${amount} | Transaction: {transaction_id}")
    logger.info("⚡ This happens in BACKGROUND - user got response 2 seconds ago!")
    logger.info("=" * 80)

    try:
        # Create email message
        msg = MIMEMultipart('alternative')
        msg['Subject'] = f"Order Confirmation - Order #{order_id}"
        msg['From'] = "noreply@ecommerce.com"
        msg['To'] = user_email

        # Email body
        html = f"""
        <html>
          <head></head>
          <body>
            <h2>Thank you for your order!</h2>
            <p>Your order has been confirmed and payment processed successfully.</p>

            <h3>Order Details:</h3>
            <ul>
              <li><strong>Order ID:</strong> #{order_id}</li>
              <li><strong>Amount:</strong> ${amount}</li>
              <li><strong>Transaction ID:</strong> {transaction_id}</li>
            </ul>

            <p>You will receive shipping updates soon.</p>

            <p><em>Generated by Email Service (Microservices Architecture)</em></p>
          </body>
        </html>
        """

        msg.attach(MIMEText(html, 'html'))

        # Simulate email sending delay (2 seconds, same as monolith)
        logger.info("💀💀 BLOCKING OPERATION - but user doesn't wait for this!")
        logger.info("⏳ Simulating 2-second email delay...")
        time.sleep(2)

        # Send email via SMTP
        with smtplib.SMTP(settings.smtp_host, settings.smtp_port) as server:
            server.send_message(msg)

        logger.info("=" * 80)
        logger.info(f"✅ Email sent successfully to {user_email}")
        logger.info("🎉 Complete async flow: Order (300ms) → Payment (1s) → Email (2s)")
        logger.info("💡 Total backend time: ~3.3s | User wait time: ~300ms!")
        logger.info("=" * 80)

        return True

    except Exception as e:
        logger.error(f"❌ Failed to send email: {e}")
        # In production: implement retry logic, dead-letter queue
        return False
